[ # DO NOT MODIFY! AUTO GENERATED BY ./utils/create-listing.sh
{
  version = "0.8.23";
  sha256 = {
    solc-static-linux = "sha256-KHJqRSKQxw4ZhPFcU60wiOfZh4PuMHCxGzZk2ndBVzI=";
    solc-macos = "sha256-4JpCmA5EZEvjOoRVyH0JWk8AKOQafd4RN/XZp2BaLWI=";
  };
}
{
  version = "0.8.22";
  sha256 = {
    solc-static-linux = "sha256-i+Cut0/BuCEykqCahMtSSkA2AlJt+H7K1fXNKn6n0Ik=";
    solc-macos = "sha256-yNO3gDwOssO900ssO5cG6djIG4gpJQ5JJF2suYSmLgU=";
  };
}
{
  version = "0.8.21";
  sha256 = {
    solc-static-linux = "sha256-8oV6iYvhXGno3lWY3NPz4WnpSWSgzpoLuxsRHxRagd8=";
    solc-macos = "sha256-GdBldJ+wjL/097RShKxVhTBjhl9q6GIeTe+l2Ti5pQI=";
  };
}
{
  version = "0.8.20";
  sha256 = {
    solc-static-linux = "sha256-BHnUT9+cUBwlM3/cVAQZ8Vk7iEqHtH8CPaTxxwD9p4I=";
    solc-macos = "sha256-/DKZReAGjk6VXQp7WDd23I0l5yq2V6BEYYp8590FGao=";
  };
}
{
  version = "0.8.19";
  sha256 = {
    solc-static-linux = "sha256-elwdPcmo66Yrsuw3GSyReK5f6KVKVuVXP9PJwXzZ60g=";
    solc-macos = "sha256-OMhSOrZ+Cz4hxIGJ1r+5mtaHm5zgLg2ALsi+WYuyYi0=";
  };
}
{
  version = "0.8.18";
  sha256 = {
    solc-static-linux = "sha256-lebtSUmmOtia+0Q+y6H7gwLdKGDuXpuqzj5nSg9Iqnc=";
    solc-macos = "sha256-jxUofHma0rM/JB0SUiJqvaXUvD72vkC5RpIxePxX05c=";
  };
}
{
  version = "0.8.17";
  sha256 = {
    solc-static-linux = "sha256-mfIHC3dulxTx92xDwinPmbiXipKTjujSNkxt4RwaA9Q=";
    solc-macos = "sha256-5A7vg8JNTEK0f0YbAXSKbKifHgnneJlbcd6/oN6Z4So=";
  };
}
{
  version = "0.8.16";
  sha256 = {
    solc-static-linux = "sha256-FjJ4bGwfhWpKiZIy7JdaEvMFEY9DzOkOck7Qsu6/7uE=";
    solc-macos = "sha256-fUccubrpp/Kcfr9AL34W+oImsXupq2iojOEHEUR53E0=";
  };
}
{
  version = "0.8.15";
  sha256 = {
    solc-static-linux = "sha256-UYkVXOMi1X+3XoUY2bOROWJ+3qT7JbXw6+0DkcUudMw=";
    solc-macos = "sha256-AGVtxzIk5MBwKUDfEDEL3AJLYPSnWY53TTBbw7lPfXk=";
  };
}
{
  version = "0.8.14";
  sha256 = {
    solc-static-linux = "sha256-1bAnyGwPj+zAJNXU+V2OpI2KlC15lwMQ40I3BTK1AvA=";
    solc-macos = "sha256-s9GatHZXrze+TFUfg0lCSOmde6EDtgcujAjbticI4rA=";
  };
}
{
  version = "0.8.13";
  sha256 = {
    solc-static-linux = "sha256-qAXf+obM2O1cnNGP/PzKb/RvY1IWqn/AJGVG975BPWI=";
    solc-macos = "sha256-FNTvAT6oKtlekf2Um3+nt4JxpIP/GnnEPWzFi4JvW+o=";
  };
}
{
  version = "0.8.12";
  sha256 = {
    solc-static-linux = "sha256-VWw+xE+vj/a2eTP6iopAOr6CyXjW5YHb/sS9BzYL+/M=";
    solc-macos = "sha256-lXOKJ5CaE1Ajhen+j489ioc9L69dBv9he8L+PtuMS/k=";
  };
}
{
  version = "0.8.11";
  sha256 = {
    solc-static-linux = "sha256-cXwjnzodw6SDTBYEagtLn0aWRmXI/6ggUabQn+dBzU8=";
    solc-macos = "sha256-EM3MjY6k3en9i5U7lYhdxzfyS4ox/qZfRxX/0Ae4AoE=";
  };
}
{
  version = "0.8.10";
  sha256 = {
    solc-static-linux = "sha256-x+/6zyi51kSV+Bt1Io+/QmasDsh+jxrcSJ3dik3QbYk=";
    solc-macos = "sha256-p5//I66zW+hW5EaCfESpz6TDgvKbq9L2pAXvc9HipMw=";
  };
}
{
  version = "0.8.9";
  sha256 = {
    solc-static-linux = "sha256-+FHxH603SWuquvjWy1wFfKDZdU/dt6NRq1gNf9coy5Q=";
    solc-macos = "sha256-1hnU9dj9mIvGMmJAfnSekFzMjYqxzPAoDaHRK5GIlM4=";
  };
}
{
  version = "0.8.8";
  sha256 = {
    solc-static-linux = "sha256-5nexIWsTbGHjiTSj3jqOZ94/cz16so8PBGvUoHiwy7A=";
    solc-macos = "sha256-FCLhBFQlHVb+9ilA+y4gmm9GeuNfc73OWAvAutNYUd0=";
  };
}
{
  version = "0.8.7";
  sha256 = {
    solc-static-linux = "sha256-AD11OD5FIS+YEtC2rdkDKf07I55sN40ogvYfk0WJbZk=";
    solc-macos = "sha256-zFxmPR/hfU60rKCSU3h6yGuHhSNfynHZIAVp5mJneZA=";
  };
}
{
  version = "0.8.6";
  sha256 = {
    solc-static-linux = "sha256-q9XE8/JivD7XlRuWjGP5joP2bZpcNWirMG6sSSUK7D4=";
    solc-macos = "sha256-hu6Z9k/H42v6BGFptqTUwQ6zUBftEeDJcPASI7L12zY=";
  };
}
{
  version = "0.8.5";
  sha256 = {
    solc-static-linux = "sha256-vXggB6fVBQDSJwMUWs5tRMkWyFPNDQ/LLK6rn6X6M+c=";
    solc-macos = "sha256-NCHuZ6Ju9Kcg55Ux/9m5be7Ine+81wu0oz6WixLduTg=";
  };
}
{
  version = "0.8.4";
  sha256 = {
    solc-static-linux = "sha256-9xFcyvEYmdzzqqiIlJ+GFEIfLRCvZadIcLz9ZwENp/g=";
    solc-macos = "sha256-T28uaUKgkFG7vIUNT6mw2Qd0lhLLXbWMrAyHdFQ1Bw8=";
  };
}
{
  version = "0.8.3";
  sha256 = {
    solc-static-linux = "sha256-+zOv12HQ1wRnHa1YLTtKeQ1NhaY3D+cbP4k1ZJaB4pI=";
    solc-macos = "sha256-EYj1wk0z7B7CzoEaekW9w8Fn8bpxy8JmQBZWTS/dRro=";
  };
}
{
  version = "0.8.2";
  sha256 = {
    solc-static-linux = "sha256-trlCnXHUOVkBeVk2oKruCyMIL8ruENVj2HtC5pwOaMI=";
    solc-macos = "sha256-CJjCOwrIzavO47ZGtnbaEgX0vnwL7IpY3oGwYMWbTBw=";
  };
}
{
  version = "0.8.1";
  sha256 = {
    solc-static-linux = "sha256-2qf21swKMWvrJgdTMYO2SQR5hnewy5m9oFSepw6N5ho=";
    solc-macos = "sha256-OFBONXYywVr+1hLCDvh4mSyoQRzj+2r+433sbr0izgI=";
  };
}
{
  version = "0.8.0";
  sha256 = {
    solc-static-linux = "sha256-ZAFjEKV8rxr3ajYQ8flMiEjATJZz5/omhJLmCJGKS9w=";
    solc-macos = "sha256-x8P/SE0t1pNQ/BgtROz2BX/yiFuWocOZDKNi6cgyUzU=";
  };
}
{
  version = "0.7.6";
  sha256 = {
    solc-static-linux = "sha256-vWnqhUJ78vTadMtCatlR3Xjbnf3QHXkSCOzMLUlYprs=";
    solc-macos = "sha256-pqj5+TiMX82SIkdOACcCQsgy6Taw9SV8IDdNJ+5b0as=";
  };
}
{
  version = "0.7.5";
  sha256 = {
    solc-static-linux = "sha256-lvsiE0wQk5M0xiyMCmaLcSaW+PgUJub88ELw5wnnqh4=";
    solc-macos = "sha256-HBAM6GoxZ/1MGUKQqv7A09lP6Gx6GqCDfBNGzJPYts4=";
  };
}
{
  version = "0.7.4";
  sha256 = {
    solc-static-linux = "sha256-4Ppqg0elK8bsNR4iU35kW+ButQQYlEYLGpEU83MunQc=";
    solc-macos = "sha256-zOACaIzxD7AkOgQlA/PpiWqpkatZsItXlx1C1o6Z+D0=";
  };
}
{
  version = "0.7.3";
  sha256 = {
    solc-static-linux = "sha256-Khfeo7F4XqxF5q8M4yivaOuUOmRjs24D0x2Z12UaKLE=";
    solc-macos = "sha256-8YUQTtXiqQs86N/HKDxdD/u3ONfI2hnoY13Z/aNMM3o=";
  };
}
{
  version = "0.7.2";
  sha256 = {
    solc-static-linux = "sha256-dZkws5bNoNF2Id1uyoqhajVwFFlgJUQx5sQugWJuWhA=";
    solc-macos = "sha256-VRhkH2xKKGBU9cnykUaXDvcvLzTudu0j9esfbR3P7Ns=";
  };
}
{
  version = "0.7.1";
  sha256 = {
    solc-static-linux = "sha256-wMSUAurxg1Pmv7j9xyYn7KXS1j+zal6nhxFN7pSXmao=";
    solc-macos = "sha256-VbgHLMasFUvyfyIXev5YvgXyjBHvUfxOZgMT0wRaQmg=";
  };
}
{
  version = "0.7.0";
  sha256 = {
    solc-static-linux = "sha256-EXRUeRkD00WHt7B2JsAyU8bURytvCfcu4AfPHyILSek=";
    solc-macos = "sha256-QFVdboJhBMrNDAtjfF+1c9W24qascBENwDM0ZsARXh0=";
  };
}
{
  version = "0.6.12";
  sha256 = {
    solc-static-linux = "sha256-9stRmwHavGHKtMGEo9sRqlkdGBUeNi/K6FDkLP/fsJo=";
    solc-macos = "sha256-Ba2K+oPfO1HTb+moTqRGez7RdYXJA5RphdbizV6VaFo=";
  };
}
{
  version = "0.6.11";
  sha256 = {
    solc-static-linux = "sha256-LgkdXxO+oLxEXH9nTVz4yeQqPU414eUPAPTdRImFBao=";
    solc-macos = "sha256-oKZKoJKmFq5xRdqQj8Qn/DwpbTr9v6jqNGiiJyLV0Bw=";
  };
}
{
  version = "0.6.10";
  sha256 = {
    solc-static-linux = "sha256-aMQUungyVXCjSBeoKbHzxioYmFcIolCXKbUPeYKaN0s=";
    solc-macos = "sha256-N3PmbD7xTi5HvdfQbzD5UsGZhW3yQNFkyRwfAIBvu8c=";
  };
}
{
  version = "0.6.9";
  sha256 = {
    solc-static-linux = "sha256-60K+9XhKDewPG1TCYLN23rBJWUC/1HTES1vjHAtjRgM=";
    solc-macos = "sha256-mPvhB1VjitXMwGg4ELlhqANFDpS2Qq8RJZMkimhapNw=";
  };
}
{
  version = "0.6.8";
  sha256 = {
    solc-static-linux = "sha256-n3YWfHhjXNBIyjDnXZ2t5X6m8NA7gzhNZA1do46MWA0=";
    # solc-macos not available for this version
  };
}
{
  version = "0.6.7";
  sha256 = {
    solc-static-linux = "sha256-ICY6oXwufKjBDs09QkLfYdudVJvB3bcrmjh8DBE2wc8=";
    # solc-macos not available for this version
  };
}
{
  version = "0.6.6";
  sha256 = {
    solc-static-linux = "sha256-XYzU4MwC6ZRkl9towG1WMmp4/5WiHJJlz+24GaEKU50=";
    # solc-macos not available for this version
  };
}
{
  version = "0.6.5";
  sha256 = {
    solc-static-linux = "sha256-Mydq3/jw5iCt9xxKtm10jQaQw0Ngzk9V4NGMd/oTR20=";
    # solc-macos not available for this version
  };
}
{
  version = "0.6.4";
  sha256 = {
    solc-static-linux = "sha256-lt3YHqfZTW5/ETX3sRqx0GNa1Vhe2UFH8f45satyZvs=";
    # solc-macos not available for this version
  };
}
{
  version = "0.6.3";
  sha256 = {
    solc-static-linux = "sha256-YB+HTipSx1ndzBB0y3XBKEjizomah0akPir/vSimVeE=";
    # solc-macos not available for this version
  };
}
{
  version = "0.6.2";
  sha256 = {
    solc-static-linux = "sha256-EJyoxrkvRUjnjHKmTEfGFGF9eyteS2+Lnn1lT8UYY2U=";
    # solc-macos not available for this version
  };
}
{
  version = "0.6.1";
  sha256 = {
    solc-static-linux = "sha256-SZwqrRMv/felnOh9iOT+zizNY/Wrfig7G+THIrBiBss=";
    # solc-macos not available for this version
  };
}
{
  version = "0.6.0";
  sha256 = {
    solc-static-linux = "sha256-XEsw2hiw+l8a4xgxJ6Tc1konn8wV4WpHewhB1XZ3AoM=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.17";
  sha256 = {
    solc-static-linux = "sha256-w1znpNP/pXR8F4seJMhUGy5dioLB2zcZ60QzofGeFvM=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.16";
  sha256 = {
    solc-static-linux = "sha256-oV8BcA7H4C+Ru9/Utv9EULPC3srhc+T0GRCjz7r109M=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.15";
  sha256 = {
    solc-static-linux = "sha256-vIFvIQTQ4xYXm85pr88kpItcbHIDy3K+ytfZ57ZpkLQ=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.14";
  sha256 = {
    solc-static-linux = "sha256-SEVOKQ7/0bmyqoYAE97/CaebTXRyh1oH8+fVR98pfsw=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.13";
  sha256 = {
    solc-static-linux = "sha256-W2IQXonCKfWVHQXysZr4EWNZnH8N7MBK+B4lOZY2aq8=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.12";
  sha256 = {
    solc-static-linux = "sha256-cLbwo1U4XFrqJsdhsuWLMhaqVk9B5OFWgTvjxHpmrpw=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.11";
  sha256 = {
    solc-static-linux = "sha256-NQ1avFhi3KQykkJrbU5ZL4H0CwLNqDPzhAa6AEe2udA=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.10";
  sha256 = {
    solc-static-linux = "sha256-PJsujrmNQpT8RTJtr8vMtGpwmTw0bH07VaoCkrPKAzQ=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.9";
  sha256 = {
    solc-static-linux = "sha256-OQ0UrEe0oB5PgEpXFZ/6UmwjKaDrCLniDe4AZJ77NGE=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.8";
  sha256 = {
    solc-static-linux = "sha256-WPvpu7cJJ3lX/RK5IlMPA89VjPgDtyMzotdtVHV4hdE=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.7";
  sha256 = {
    solc-static-linux = "sha256-gQxSz/KVEflcRPmhrisRwEWY1BPW/6N72xlBWSb7Wzc=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.6";
  sha256 = {
    solc-static-linux = "sha256-88cKTXFre06BHvUgSzrmoWSXrnAaK4YmDRve5+RIS1M=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.5";
  sha256 = {
    solc-static-linux = "sha256-cYx8xYGKkXnTYMpUIsnxOjEqK6+IhPPdi74yh+yu8MY=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.4";
  sha256 = {
    solc-static-linux = "sha256-D940fbXmMvw67zyo2nSJbY33o1KHZG5/ve6Cn+I2BUo=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.3";
  sha256 = {
    solc-static-linux = "sha256-vgjrlcs6HaUukYz1GgwDl/vn8GkxResxg1vykkIJ8eA=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.2";
  sha256 = {
    solc-static-linux = "sha256-hxRqeyhLHJBnqRWTDAxq98mf+d0YB+NoA2f8A6Weg78=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.1";
  sha256 = {
    solc-static-linux = "sha256-YnXUgfIxgOALOJloSFNNt4tPc8qsoVQ1rYYd9UW7cdA=";
    # solc-macos not available for this version
  };
}
{
  version = "0.5.0";
  sha256 = {
    solc-static-linux = "sha256-wbsVtSD1B2rr16qe9M5fokW28hCpHL0gZLnjg+ZRDgg=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.26";
  sha256 = {
    solc-static-linux = "sha256-n52loS/KJ411Fl9Mp17p0pDZ8L2Mq9WfFr85zwrGIZI=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.25";
  sha256 = {
    solc-static-linux = "sha256-ybJodQUGuI/nE3EQAFDp3R5+3Pj2naNNHNCVV+yyRYA=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.24";
  sha256 = {
    solc-static-linux = "sha256-ZlZ1ueBDHCVy1Z1qcRKvvcdScy6gzprs8aGFXyjgKgk=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.23";
  sha256 = {
    solc-static-linux = "sha256-xkjSmb0h9MdM4XlUcGz8Wnqfu9Hoc5VG7YdUys2Mp8I=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.22";
  sha256 = {
    solc-static-linux = "sha256-+t6bpt1In/w/c+U6E9XxAxMld5cI5EgiSXCXm4zIa6c=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.21";
  sha256 = {
    solc-static-linux = "sha256-kFIoUFQgzTHmOT4J6mhbh1hbYsQznTrdwKMEm+u8QzI=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.20";
  sha256 = {
    solc-static-linux = "sha256-2Wa4IVpPgzd86dYiyRmP6R5bkzAGUr8IGq8vaqOsahY=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.19";
  sha256 = {
    solc-static-linux = "sha256-B/iXU83aKAVLtvFZohkRcWyutDs8dlmiXx8tndF7yCc=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.18";
  sha256 = {
    solc-static-linux = "sha256-iYpeBdOsCNcmsBnSQVwcCHqa6HhmzfpVHAiza2tFMh0=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.17";
  sha256 = {
    solc-static-linux = "sha256-E0FL+G+AMZ5vWGO0ykr3hpVtGI9fm5ndpkOTYsbZERU=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.16";
  sha256 = {
    solc-static-linux = "sha256-eODabK0kqxRajRdCDE8JTIMUQYyiPP9LBQuyv9NvOvI=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.15";
  sha256 = {
    solc-static-linux = "sha256-xxrGwovzsaQl536X9d9nqA2j5MBHJhh1IGVhwKEQwMs=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.14";
  sha256 = {
    solc-static-linux = "sha256-KM41oJQdns1ZorGjd8AZEQ55prOL2/Wjv/6oEfnCoTs=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.13";
  sha256 = {
    solc-static-linux = "sha256-eR7jogrfbFq3bMiJ8TzKEC926wt88NpKC1sR3Ebt80k=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.12";
  sha256 = {
    solc-static-linux = "sha256-IhrjPhK9pci3lsmrrisutz5G2bEhKL/uRRsShW+LR+4=";
    # solc-macos not available for this version
  };
}
{
  version = "0.4.11";
  sha256 = {
    solc-static-linux = "sha256-Co0TjuJFA55vgxLtwCS6PEc5zDwBO0fcf8kZai4yf+o=";
    # solc-macos not available for this version
  };
}
]
