[ # DO NOT MODIFY! AUTO GENERATED BY ./utils/create-listing.sh
{
  version = "0.8.31";
  sha256 = {
    solc-static-linux = "sha256-qsnNARbprgzT2PZKhkE4GEXcnxLipSZT3jb7YZMj5Vc=";
    solc-macos-amd64 = "sha256-9aJD1rLdj7owfjbF/votjrOudLqBA20cF8lxtdNGrek=";
    solc-macos-aarch64 = "sha256-9aJD1rLdj7owfjbF/votjrOudLqBA20cF8lxtdNGrek=";
  };
}
{
  version = "0.8.30";
  sha256 = {
    solc-static-linux = "sha256-8+mH3G7OvUvTUMSO3LwyC0bPnjEJvT/D2I8ayvTEKPc=";
    solc-macos-amd64 = "sha256-c43Nxq/d61Be5OTvJPHB/borjJJOYUy79YAaWwYt1oM=";
    solc-macos-aarch64 = "sha256-c43Nxq/d61Be5OTvJPHB/borjJJOYUy79YAaWwYt1oM=";
  };
}
{
  version = "0.8.29";
  sha256 = {
    solc-static-linux = "sha256-GNQYpA3ATRdlaxtcins1z7q4lCtR840AXVtZ6KpmN+A=";
    solc-macos-amd64 = "sha256-Zvq90XyMAJExGZfsfRe02S4beywtIT3BTk/yjD3oZNE=";
    solc-macos-aarch64 = "sha256-Zvq90XyMAJExGZfsfRe02S4beywtIT3BTk/yjD3oZNE=";
  };
}
{
  version = "0.8.28";
  sha256 = {
    solc-static-linux = "sha256-mg+34NssBkHbrhxcxkXcaGggyDr1FiJquxwKL3ZjbyU=";
    solc-macos-amd64 = "sha256-gVFbDlPeqiZtVJVFzKrApalubU6CAcd/ZzsscQl22eo=";
    solc-macos-aarch64 = "sha256-gVFbDlPeqiZtVJVFzKrApalubU6CAcd/ZzsscQl22eo=";
  };
}
{
  version = "0.8.27";
  sha256 = {
    solc-static-linux = "sha256-uZd9UAwXy6bwAyypOe+YxN7PY2PxnzhtBfsC9wgRUmQ=";
    solc-macos-amd64 = "sha256-jEBvpcq5vQoXXaAsZSBy+BTD0GIFov1tkrwVJZmmqrs=";
    solc-macos-aarch64 = "sha256-jEBvpcq5vQoXXaAsZSBy+BTD0GIFov1tkrwVJZmmqrs=";
  };
}
{
  version = "0.8.26";
  sha256 = {
    solc-static-linux = "sha256-1fI0NvRD7bhdjnaQbRLwqGzgSQ52Y6nmCO/repPxSe8=";
    solc-macos-amd64 = "sha256-D/AWrvI5axLR/GVCnY6mz1PC7ksEG7iSVkRhXuHDCrk=";
    solc-macos-aarch64 = "sha256-D/AWrvI5axLR/GVCnY6mz1PC7ksEG7iSVkRhXuHDCrk=";
  };
}
{
  version = "0.8.25";
  sha256 = {
    solc-static-linux = "sha256-xCqtp6UgV92+2T7AESNeJWxWTEQLaNuqxa5IK6u7PW0=";
    solc-macos-amd64 = "sha256-zD+UpwrGgbAwQISswZgKq+KhuzJA1Eznao3w4ed6IRA=";
    solc-macos-aarch64 = "sha256-zD+UpwrGgbAwQISswZgKq+KhuzJA1Eznao3w4ed6IRA=";
  };
}
{
  version = "0.8.24";
  sha256 = {
    solc-static-linux = "sha256-+wOimlF0UrnxK89FnvN9ClQ3Zbs7vJEecKh9ajfDDV8=";
    solc-macos-amd64 = "sha256-zC1ExwaQXMw4L0hGJd/2HXQeDCQjLSJvE5poNfxkTz8=";
    solc-macos-aarch64 = "sha256-zC1ExwaQXMw4L0hGJd/2HXQeDCQjLSJvE5poNfxkTz8=";
  };
}
{
  version = "0.8.23";
  sha256 = {
    solc-static-linux = "sha256-KHJqRSKQxw4ZhPFcU60wiOfZh4PuMHCxGzZk2ndBVzI=";
    solc-macos-amd64 = "sha256-4JpCmA5EZEvjOoRVyH0JWk8AKOQafd4RN/XZp2BaLWI=";
    solc-macos-aarch64 = "sha256-35D9WAySlw5kQfpLabWONk4z8e8Nprja5JryielyoHU=";
  };
}
{
  version = "0.8.22";
  sha256 = {
    solc-static-linux = "sha256-i+Cut0/BuCEykqCahMtSSkA2AlJt+H7K1fXNKn6n0Ik=";
    solc-macos-amd64 = "sha256-yNO3gDwOssO900ssO5cG6djIG4gpJQ5JJF2suYSmLgU=";
    solc-macos-aarch64 = "sha256-KhkJcPk/P482Md9uq9JFmU/8VVjo772U1Zem9Ef1mzM=";
  };
}
{
  version = "0.8.21";
  sha256 = {
    solc-static-linux = "sha256-8oV6iYvhXGno3lWY3NPz4WnpSWSgzpoLuxsRHxRagd8=";
    solc-macos-amd64 = "sha256-GdBldJ+wjL/097RShKxVhTBjhl9q6GIeTe+l2Ti5pQI=";
    solc-macos-aarch64 = "sha256-U6DH2V0S8FvkKi5fb86VCdYjFGS9ASBRiku0rjMteRI=";
  };
}
{
  version = "0.8.20";
  sha256 = {
    solc-static-linux = "sha256-BHnUT9+cUBwlM3/cVAQZ8Vk7iEqHtH8CPaTxxwD9p4I=";
    solc-macos-amd64 = "sha256-/DKZReAGjk6VXQp7WDd23I0l5yq2V6BEYYp8590FGao=";
    solc-macos-aarch64 = "sha256-XZjJ7YkrdOytxKt/k95iEf3eA1HvZvLLkOsRYw4w4qs=";
  };
}
{
  version = "0.8.19";
  sha256 = {
    solc-static-linux = "sha256-elwdPcmo66Yrsuw3GSyReK5f6KVKVuVXP9PJwXzZ60g=";
    solc-macos-amd64 = "sha256-OMhSOrZ+Cz4hxIGJ1r+5mtaHm5zgLg2ALsi+WYuyYi0=";
    solc-macos-aarch64 = "sha256-SeGuVTTNDl1Hp8D7j+vmRbsCwcLVCSYzQq+7BCoN964=";
  };
}
{
  version = "0.8.18";
  sha256 = {
    solc-static-linux = "sha256-lebtSUmmOtia+0Q+y6H7gwLdKGDuXpuqzj5nSg9Iqnc=";
    solc-macos-amd64 = "sha256-jxUofHma0rM/JB0SUiJqvaXUvD72vkC5RpIxePxX05c=";
    solc-macos-aarch64 = "sha256-V4Sxf7qM5AMPLImhMLMItstdJDaWq0jbLdYPSbAAVpg=";
  };
}
{
  version = "0.8.17";
  sha256 = {
    solc-static-linux = "sha256-mfIHC3dulxTx92xDwinPmbiXipKTjujSNkxt4RwaA9Q=";
    solc-macos-amd64 = "sha256-5A7vg8JNTEK0f0YbAXSKbKifHgnneJlbcd6/oN6Z4So=";
    solc-macos-aarch64 = "sha256-9aOOn4cO8uAOcUYwITuyXlDggPa3cqclNzjmR2IbpOY=";
  };
}
{
  version = "0.8.16";
  sha256 = {
    solc-static-linux = "sha256-FjJ4bGwfhWpKiZIy7JdaEvMFEY9DzOkOck7Qsu6/7uE=";
    solc-macos-amd64 = "sha256-fUccubrpp/Kcfr9AL34W+oImsXupq2iojOEHEUR53E0=";
    solc-macos-aarch64 = "sha256-sb5g1lBG+fi8WLks/R9EClQWfp/uNAtWjGFg6oVU0RE=";
  };
}
{
  version = "0.8.15";
  sha256 = {
    solc-static-linux = "sha256-UYkVXOMi1X+3XoUY2bOROWJ+3qT7JbXw6+0DkcUudMw=";
    solc-macos-amd64 = "sha256-AGVtxzIk5MBwKUDfEDEL3AJLYPSnWY53TTBbw7lPfXk=";
    solc-macos-aarch64 = "sha256-C2YZ7hSvVqt6b1mT9C0tcAqh3ab5+yx09d9S7rY2kwc=";
  };
}
{
  version = "0.8.14";
  sha256 = {
    solc-static-linux = "sha256-1bAnyGwPj+zAJNXU+V2OpI2KlC15lwMQ40I3BTK1AvA=";
    solc-macos-amd64 = "sha256-s9GatHZXrze+TFUfg0lCSOmde6EDtgcujAjbticI4rA=";
    solc-macos-aarch64 = "sha256-t2+hD60EXRNz3VfFGaRycZLcBLzv/oY/vbAVY4/kZ74=";
  };
}
{
  version = "0.8.13";
  sha256 = {
    solc-static-linux = "sha256-qAXf+obM2O1cnNGP/PzKb/RvY1IWqn/AJGVG975BPWI=";
    solc-macos-amd64 = "sha256-FNTvAT6oKtlekf2Um3+nt4JxpIP/GnnEPWzFi4JvW+o=";
    solc-macos-aarch64 = "sha256-QoN79Wjo63d8azdsTuUlKT90BfgrnGVqEJPUKzrCpaY=";
  };
}
{
  version = "0.8.12";
  sha256 = {
    solc-static-linux = "sha256-VWw+xE+vj/a2eTP6iopAOr6CyXjW5YHb/sS9BzYL+/M=";
    solc-macos-amd64 = "sha256-lXOKJ5CaE1Ajhen+j489ioc9L69dBv9he8L+PtuMS/k=";
    solc-macos-aarch64 = "sha256-ez+u2xfBcJZBh30afn1U6vcTkp+tvIvlzJ2eJKuLnMc=";
  };
}
{
  version = "0.8.11";
  sha256 = {
    solc-static-linux = "sha256-cXwjnzodw6SDTBYEagtLn0aWRmXI/6ggUabQn+dBzU8=";
    solc-macos-amd64 = "sha256-EM3MjY6k3en9i5U7lYhdxzfyS4ox/qZfRxX/0Ae4AoE=";
    solc-macos-aarch64 = "sha256-X9A8t6nTlZ6jOLjETxTugRUfswsqdjt6/DDFWtB/T+U=";
  };
}
{
  version = "0.8.10";
  sha256 = {
    solc-static-linux = "sha256-x+/6zyi51kSV+Bt1Io+/QmasDsh+jxrcSJ3dik3QbYk=";
    solc-macos-amd64 = "sha256-p5//I66zW+hW5EaCfESpz6TDgvKbq9L2pAXvc9HipMw=";
    solc-macos-aarch64 = "sha256-k+qHA0/grzsqhMy58sB14hoFu0XXDKjHLSGqvtrmXQ4=";
  };
}
{
  version = "0.8.9";
  sha256 = {
    solc-static-linux = "sha256-+FHxH603SWuquvjWy1wFfKDZdU/dt6NRq1gNf9coy5Q=";
    solc-macos-amd64 = "sha256-1hnU9dj9mIvGMmJAfnSekFzMjYqxzPAoDaHRK5GIlM4=";
    solc-macos-aarch64 = "sha256-WZb+gMihrCj2AQzqPMuxwrvQ4lOR5Sxig5tvoF0efqw=";
  };
}
{
  version = "0.8.8";
  sha256 = {
    solc-static-linux = "sha256-5nexIWsTbGHjiTSj3jqOZ94/cz16so8PBGvUoHiwy7A=";
    solc-macos-amd64 = "sha256-FCLhBFQlHVb+9ilA+y4gmm9GeuNfc73OWAvAutNYUd0=";
    solc-macos-aarch64 = "sha256-V3DA9CFkb66WTFWCPfE7QmVQAQAZFlkcrUcgdQJUtlc=";
  };
}
{
  version = "0.8.7";
  sha256 = {
    solc-static-linux = "sha256-AD11OD5FIS+YEtC2rdkDKf07I55sN40ogvYfk0WJbZk=";
    solc-macos-amd64 = "sha256-zFxmPR/hfU60rKCSU3h6yGuHhSNfynHZIAVp5mJneZA=";
    solc-macos-aarch64 = "sha256-DKHiTDR1baPe/JKeyQbbPlDW9R6CzDxgeMjdAK0uyjo=";
  };
}
{
  version = "0.8.6";
  sha256 = {
    solc-static-linux = "sha256-q9XE8/JivD7XlRuWjGP5joP2bZpcNWirMG6sSSUK7D4=";
    solc-macos-amd64 = "sha256-hu6Z9k/H42v6BGFptqTUwQ6zUBftEeDJcPASI7L12zY=";
    solc-macos-aarch64 = "sha256-UA1Kx+/vgEd+xy872P01pspO6hy9nklZ0nDGD0iJolo=";
  };
}
{
  version = "0.8.5";
  sha256 = {
    solc-static-linux = "sha256-vXggB6fVBQDSJwMUWs5tRMkWyFPNDQ/LLK6rn6X6M+c=";
    solc-macos-amd64 = "sha256-NCHuZ6Ju9Kcg55Ux/9m5be7Ine+81wu0oz6WixLduTg=";
    solc-macos-aarch64 = "sha256-+qzRm8nEC1fbLfAH+6IHtEdEHzKz0V8HiS1H4LmJrbE=";
  };
}
{
  version = "0.8.4";
  sha256 = {
    solc-static-linux = "sha256-9xFcyvEYmdzzqqiIlJ+GFEIfLRCvZadIcLz9ZwENp/g=";
    solc-macos-amd64 = "sha256-T28uaUKgkFG7vIUNT6mw2Qd0lhLLXbWMrAyHdFQ1Bw8=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.8.3";
  sha256 = {
    solc-static-linux = "sha256-+zOv12HQ1wRnHa1YLTtKeQ1NhaY3D+cbP4k1ZJaB4pI=";
    solc-macos-amd64 = "sha256-EYj1wk0z7B7CzoEaekW9w8Fn8bpxy8JmQBZWTS/dRro=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.8.2";
  sha256 = {
    solc-static-linux = "sha256-trlCnXHUOVkBeVk2oKruCyMIL8ruENVj2HtC5pwOaMI=";
    solc-macos-amd64 = "sha256-CJjCOwrIzavO47ZGtnbaEgX0vnwL7IpY3oGwYMWbTBw=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.8.1";
  sha256 = {
    solc-static-linux = "sha256-2qf21swKMWvrJgdTMYO2SQR5hnewy5m9oFSepw6N5ho=";
    solc-macos-amd64 = "sha256-OFBONXYywVr+1hLCDvh4mSyoQRzj+2r+433sbr0izgI=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.8.0";
  sha256 = {
    solc-static-linux = "sha256-ZAFjEKV8rxr3ajYQ8flMiEjATJZz5/omhJLmCJGKS9w=";
    solc-macos-amd64 = "sha256-x8P/SE0t1pNQ/BgtROz2BX/yiFuWocOZDKNi6cgyUzU=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.7.6";
  sha256 = {
    solc-static-linux = "sha256-vWnqhUJ78vTadMtCatlR3Xjbnf3QHXkSCOzMLUlYprs=";
    solc-macos-amd64 = "sha256-pqj5+TiMX82SIkdOACcCQsgy6Taw9SV8IDdNJ+5b0as=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.7.5";
  sha256 = {
    solc-static-linux = "sha256-lvsiE0wQk5M0xiyMCmaLcSaW+PgUJub88ELw5wnnqh4=";
    solc-macos-amd64 = "sha256-HBAM6GoxZ/1MGUKQqv7A09lP6Gx6GqCDfBNGzJPYts4=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.7.4";
  sha256 = {
    solc-static-linux = "sha256-4Ppqg0elK8bsNR4iU35kW+ButQQYlEYLGpEU83MunQc=";
    solc-macos-amd64 = "sha256-zOACaIzxD7AkOgQlA/PpiWqpkatZsItXlx1C1o6Z+D0=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.7.3";
  sha256 = {
    solc-static-linux = "sha256-Khfeo7F4XqxF5q8M4yivaOuUOmRjs24D0x2Z12UaKLE=";
    solc-macos-amd64 = "sha256-8YUQTtXiqQs86N/HKDxdD/u3ONfI2hnoY13Z/aNMM3o=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.7.2";
  sha256 = {
    solc-static-linux = "sha256-dZkws5bNoNF2Id1uyoqhajVwFFlgJUQx5sQugWJuWhA=";
    solc-macos-amd64 = "sha256-VRhkH2xKKGBU9cnykUaXDvcvLzTudu0j9esfbR3P7Ns=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.7.1";
  sha256 = {
    solc-static-linux = "sha256-wMSUAurxg1Pmv7j9xyYn7KXS1j+zal6nhxFN7pSXmao=";
    solc-macos-amd64 = "sha256-VbgHLMasFUvyfyIXev5YvgXyjBHvUfxOZgMT0wRaQmg=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.7.0";
  sha256 = {
    solc-static-linux = "sha256-EXRUeRkD00WHt7B2JsAyU8bURytvCfcu4AfPHyILSek=";
    solc-macos-amd64 = "sha256-QFVdboJhBMrNDAtjfF+1c9W24qascBENwDM0ZsARXh0=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.12";
  sha256 = {
    solc-static-linux = "sha256-9stRmwHavGHKtMGEo9sRqlkdGBUeNi/K6FDkLP/fsJo=";
    solc-macos-amd64 = "sha256-Ba2K+oPfO1HTb+moTqRGez7RdYXJA5RphdbizV6VaFo=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.11";
  sha256 = {
    solc-static-linux = "sha256-LgkdXxO+oLxEXH9nTVz4yeQqPU414eUPAPTdRImFBao=";
    solc-macos-amd64 = "sha256-oKZKoJKmFq5xRdqQj8Qn/DwpbTr9v6jqNGiiJyLV0Bw=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.10";
  sha256 = {
    solc-static-linux = "sha256-aMQUungyVXCjSBeoKbHzxioYmFcIolCXKbUPeYKaN0s=";
    solc-macos-amd64 = "sha256-N3PmbD7xTi5HvdfQbzD5UsGZhW3yQNFkyRwfAIBvu8c=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.9";
  sha256 = {
    solc-static-linux = "sha256-60K+9XhKDewPG1TCYLN23rBJWUC/1HTES1vjHAtjRgM=";
    solc-macos-amd64 = "sha256-mPvhB1VjitXMwGg4ELlhqANFDpS2Qq8RJZMkimhapNw=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.8";
  sha256 = {
    solc-static-linux = "sha256-n3YWfHhjXNBIyjDnXZ2t5X6m8NA7gzhNZA1do46MWA0=";
    solc-macos-amd64 = "sha256-gB76o9AohjcCFmfA0RbuKzOeYs8mAn+MFoJZ4IBei2A=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.7";
  sha256 = {
    solc-static-linux = "sha256-ICY6oXwufKjBDs09QkLfYdudVJvB3bcrmjh8DBE2wc8=";
    solc-macos-amd64 = "sha256-u3i23j3322EVoQMzRsPp34prnE/QOMwS1r3xar0pyVI=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.6";
  sha256 = {
    solc-static-linux = "sha256-XYzU4MwC6ZRkl9towG1WMmp4/5WiHJJlz+24GaEKU50=";
    solc-macos-amd64 = "sha256-Rcf5Vhl84Itp95PqYQzx7mXhK2pRjWFgzCjI7v9BUXw=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.5";
  sha256 = {
    solc-static-linux = "sha256-Mydq3/jw5iCt9xxKtm10jQaQw0Ngzk9V4NGMd/oTR20=";
    solc-macos-amd64 = "sha256-qBKSVLUke74APW5U81wLuoU2lBJnRFdyiba98dNaHko=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.4";
  sha256 = {
    solc-static-linux = "sha256-lt3YHqfZTW5/ETX3sRqx0GNa1Vhe2UFH8f45satyZvs=";
    solc-macos-amd64 = "sha256-CC/ULMlsKCYkWTBvKFT+cEnMDRRHPhJrLbbTC/AvVNA=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.3";
  sha256 = {
    solc-static-linux = "sha256-YB+HTipSx1ndzBB0y3XBKEjizomah0akPir/vSimVeE=";
    solc-macos-amd64 = "sha256-oJNQ1aGCs9p5nCA9Ha3Ezg5v47ltye4cnXPpqdlZLio=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.2";
  sha256 = {
    solc-static-linux = "sha256-EJyoxrkvRUjnjHKmTEfGFGF9eyteS2+Lnn1lT8UYY2U=";
    solc-macos-amd64 = "sha256-K7GdjNaaMoVKzOEkW0SSz8W151HTItLGVW1KUhv8w8g=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.1";
  sha256 = {
    solc-static-linux = "sha256-SZwqrRMv/felnOh9iOT+zizNY/Wrfig7G+THIrBiBss=";
    solc-macos-amd64 = "sha256-8WSb/bDm5TvidYVEg2JYy00C4LOBqeQyFqorL60Mm44=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.6.0";
  sha256 = {
    solc-static-linux = "sha256-XEsw2hiw+l8a4xgxJ6Tc1konn8wV4WpHewhB1XZ3AoM=";
    solc-macos-amd64 = "sha256-N77tjIuUfrpkTP2MIERuG6XXQFXmhWtkbdatS7Rw2a4=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.17";
  sha256 = {
    solc-static-linux = "sha256-w1znpNP/pXR8F4seJMhUGy5dioLB2zcZ60QzofGeFvM=";
    solc-macos-amd64 = "sha256-Nb4o9oSItx8d5mFI+RW5HWTgYpAOT8F1vy64+5SIEL0=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.16";
  sha256 = {
    solc-static-linux = "sha256-oV8BcA7H4C+Ru9/Utv9EULPC3srhc+T0GRCjz7r109M=";
    solc-macos-amd64 = "sha256-n2Yk5AhJcUK70p7+B0TuJeRFrrfJMr5AHAvDBHimu3U=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.15";
  sha256 = {
    solc-static-linux = "sha256-vIFvIQTQ4xYXm85pr88kpItcbHIDy3K+ytfZ57ZpkLQ=";
    solc-macos-amd64 = "sha256-ngUFHD1CpJyEcMvtHyv6if526TCp5VWMUs5WU895TiU=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.14";
  sha256 = {
    solc-static-linux = "sha256-SEVOKQ7/0bmyqoYAE97/CaebTXRyh1oH8+fVR98pfsw=";
    solc-macos-amd64 = "sha256-ivqSa2u4rUkvslB4sdzgn9Bfqldl5OKyZys8mc9x7rE=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.13";
  sha256 = {
    solc-static-linux = "sha256-W2IQXonCKfWVHQXysZr4EWNZnH8N7MBK+B4lOZY2aq8=";
    solc-macos-amd64 = "sha256-aKNE2d5AsNdIIInud0jkMIjFLjsQhIDYAbNMZAIL60g=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.12";
  sha256 = {
    solc-static-linux = "sha256-cLbwo1U4XFrqJsdhsuWLMhaqVk9B5OFWgTvjxHpmrpw=";
    solc-macos-amd64 = "sha256-PfuXvJQUkq+up/QEw/ucb+IVszhqpuA3B5G1ceRnlUg=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.11";
  sha256 = {
    solc-static-linux = "sha256-NQ1avFhi3KQykkJrbU5ZL4H0CwLNqDPzhAa6AEe2udA=";
    solc-macos-amd64 = "sha256-Do7ondsQlrgcNOEb21mFgi50nTqdxOchi6JHSvpkAMs=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.10";
  sha256 = {
    solc-static-linux = "sha256-PJsujrmNQpT8RTJtr8vMtGpwmTw0bH07VaoCkrPKAzQ=";
    solc-macos-amd64 = "sha256-UIK7XEkso1tosMPiTVk0tW063YPxQAupVlTo8WPHQf8=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.9";
  sha256 = {
    solc-static-linux = "sha256-OQ0UrEe0oB5PgEpXFZ/6UmwjKaDrCLniDe4AZJ77NGE=";
    solc-macos-amd64 = "sha256-kuNoggfAwrhr2dEAiDQOSlheKeOojRz3nCBD9PnxIcQ=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.8";
  sha256 = {
    solc-static-linux = "sha256-WPvpu7cJJ3lX/RK5IlMPA89VjPgDtyMzotdtVHV4hdE=";
    solc-macos-amd64 = "sha256-nzg4lshQbNlqxe+cl9erHDhftfR3Kl89LPhxXK55NVQ=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.7";
  sha256 = {
    solc-static-linux = "sha256-gQxSz/KVEflcRPmhrisRwEWY1BPW/6N72xlBWSb7Wzc=";
    solc-macos-amd64 = "sha256-p9a448si2QeJp5tIS3If4ClD+J6bfploY+3S1AuntSQ=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.6";
  sha256 = {
    solc-static-linux = "sha256-88cKTXFre06BHvUgSzrmoWSXrnAaK4YmDRve5+RIS1M=";
    solc-macos-amd64 = "sha256-Qo+cCHPYh0AkL2/Bajrm+Rs19z3fdna11bOWh9nZt9w=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.5";
  sha256 = {
    solc-static-linux = "sha256-cYx8xYGKkXnTYMpUIsnxOjEqK6+IhPPdi74yh+yu8MY=";
    solc-macos-amd64 = "sha256-f8BgDMFQAgQCyVOewK1YTrknGy0OC/+eO01MpnK+NFI=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.4";
  sha256 = {
    solc-static-linux = "sha256-D940fbXmMvw67zyo2nSJbY33o1KHZG5/ve6Cn+I2BUo=";
    solc-macos-amd64 = "sha256-Mqiv+pltBcVSVzF8xwC55bQ3fZSRm1kFVWTrC1+UF3M=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.3";
  sha256 = {
    solc-static-linux = "sha256-vgjrlcs6HaUukYz1GgwDl/vn8GkxResxg1vykkIJ8eA=";
    solc-macos-amd64 = "sha256-A6bPotdOV+o47ug86aPqN6blCSjX8QnnSzfK4xMZrys=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.2";
  sha256 = {
    solc-static-linux = "sha256-hxRqeyhLHJBnqRWTDAxq98mf+d0YB+NoA2f8A6Weg78=";
    solc-macos-amd64 = "sha256-nn7lTwvCl4+oc4uWA9Y2cVoGnYR3F3jWGVV3u5Hsucg=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.1";
  sha256 = {
    solc-static-linux = "sha256-YnXUgfIxgOALOJloSFNNt4tPc8qsoVQ1rYYd9UW7cdA=";
    solc-macos-amd64 = "sha256-8rrUM4YGVoS04VuGoXVBD10eTSNLBSy6ROtQ9MdLAh8=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.5.0";
  sha256 = {
    solc-static-linux = "sha256-wbsVtSD1B2rr16qe9M5fokW28hCpHL0gZLnjg+ZRDgg=";
    solc-macos-amd64 = "sha256-n6Zj/EJ+jpYTgVrWuDeDtOTLEEOfFsoNyxL8ACxFq1o=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.26";
  sha256 = {
    solc-static-linux = "sha256-n52loS/KJ411Fl9Mp17p0pDZ8L2Mq9WfFr85zwrGIZI=";
    solc-macos-amd64 = "sha256-vJVmRbeS3LuPgguAEKjU7B4Yj3tAxq+VGkNtpME65nc=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.25";
  sha256 = {
    solc-static-linux = "sha256-ybJodQUGuI/nE3EQAFDp3R5+3Pj2naNNHNCVV+yyRYA=";
    solc-macos-amd64 = "sha256-nddoaXUgC+cc5zHxU4I+fqDWgQbzNU6hb+zVl19cmLc=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.24";
  sha256 = {
    solc-static-linux = "sha256-ZlZ1ueBDHCVy1Z1qcRKvvcdScy6gzprs8aGFXyjgKgk=";
    solc-macos-amd64 = "sha256-cDTEBIvHE9XBTN1mgZU8c24q29uRdPi/v7aglxCf+qo=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.23";
  sha256 = {
    solc-static-linux = "sha256-xkjSmb0h9MdM4XlUcGz8Wnqfu9Hoc5VG7YdUys2Mp8I=";
    solc-macos-amd64 = "sha256-UC7dsXf5Jo15seBeas+y8ilHGCO/ZxHv9BHSoj6MwLE=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.22";
  sha256 = {
    solc-static-linux = "sha256-+t6bpt1In/w/c+U6E9XxAxMld5cI5EgiSXCXm4zIa6c=";
    solc-macos-amd64 = "sha256-qTQa3XpPAcUtuza7QCgQRnbGhLC2ADos2d2EoqmAK1k=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.21";
  sha256 = {
    solc-static-linux = "sha256-kFIoUFQgzTHmOT4J6mhbh1hbYsQznTrdwKMEm+u8QzI=";
    solc-macos-amd64 = "sha256-4DXLmoG14+Eae5nq1vUaPvdyl5TuvuRwqWTiwI4wuFc=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.20";
  sha256 = {
    solc-static-linux = "sha256-2Wa4IVpPgzd86dYiyRmP6R5bkzAGUr8IGq8vaqOsahY=";
    solc-macos-amd64 = "sha256-R0JeM4uUYdPmSYoLDVwrnMfPmY5KppEm6p9kwKF25gU=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.19";
  sha256 = {
    solc-static-linux = "sha256-B/iXU83aKAVLtvFZohkRcWyutDs8dlmiXx8tndF7yCc=";
    solc-macos-amd64 = "sha256-rOUQemj6dWNOJoSNbSCLgIp2zE+SYuU+ijYivO/U3K8=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.18";
  sha256 = {
    solc-static-linux = "sha256-iYpeBdOsCNcmsBnSQVwcCHqa6HhmzfpVHAiza2tFMh0=";
    solc-macos-amd64 = "sha256-3dyGaD0S0PAWtdV5nthPbyp59mfruTK5qOa/6aSMMZA=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.17";
  sha256 = {
    solc-static-linux = "sha256-E0FL+G+AMZ5vWGO0ykr3hpVtGI9fm5ndpkOTYsbZERU=";
    solc-macos-amd64 = "sha256-RYw+LeL/5gm3nZzcTrMIDW7XZi7xvdfIoD+xjxypoTc=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.16";
  sha256 = {
    solc-static-linux = "sha256-eODabK0kqxRajRdCDE8JTIMUQYyiPP9LBQuyv9NvOvI=";
    solc-macos-amd64 = "sha256-okUSruFmUsRGmXlxW73KpsSvq7lLcXu0CYDkstJcRwk=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.15";
  sha256 = {
    solc-static-linux = "sha256-xxrGwovzsaQl536X9d9nqA2j5MBHJhh1IGVhwKEQwMs=";
    solc-macos-amd64 = "sha256-5EmkmA20/xjn/+cEtACDze2WzM8zmGv2prtv6SXrhsA=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.14";
  sha256 = {
    solc-static-linux = "sha256-KM41oJQdns1ZorGjd8AZEQ55prOL2/Wjv/6oEfnCoTs=";
    solc-macos-amd64 = "sha256-pO8i2dNudRUb3WRyDmnt31dQCIPdYjxXgF7bXMtkSok=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.13";
  sha256 = {
    solc-static-linux = "sha256-eR7jogrfbFq3bMiJ8TzKEC926wt88NpKC1sR3Ebt80k=";
    solc-macos-amd64 = "sha256-cB7r8ON9Fyy4KdweZcdKRrO5ZzfzhmdY+YlGlqY5trc=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.12";
  sha256 = {
    solc-static-linux = "sha256-IhrjPhK9pci3lsmrrisutz5G2bEhKL/uRRsShW+LR+4=";
    solc-macos-amd64 = "sha256-ZcySyRjWM09TOnWW9ikWgl/HIrKnojVynth8++xiK80=";
    # solc-macos-aarch64 not available for this version
  };
}
{
  version = "0.4.11";
  sha256 = {
    solc-static-linux = "sha256-Co0TjuJFA55vgxLtwCS6PEc5zDwBO0fcf8kZai4yf+o=";
    solc-macos-amd64 = "sha256-KH6rAYfdS97FAibzFzUmvY0ket7r32S8C3RIcRq76mE=";
    # solc-macos-aarch64 not available for this version
  };
}
]
