#!/usr/bin/env bash

T=$(dirname "$0")/..
[[ -e "$T/bin" ]] || { echo "Symlink or create a top-level bin folder" && exit 1; }

c="$T"/bin

print_hash() {
    t="$1"
    f="$2"
    if [[ -f "$f" ]]; then
        rp=$(realpath "$f")
        echo "$t = \"$(nix hash file "$rp")\";"
    else
        echo "# $t not available for this version";
    fi
}

{
    echo "[ # DO NOT MODIFY! AUTO GENERATED BY $0"
    # sort --version-sort is a miracle...
    # shellcheck disable=SC2012
    ls "$T"/bin/static-linux | sort --reverse --version-sort | while read -r s; do
        cat <<EOF
{
  version = "${s#solc-}";
  sha256 = {
    $(print_hash solc-static-linux  "$c"/static-linux/"$s")
    $(print_hash solc-macos-amd64   "$c"/macos-amd64/"$s")
    $(print_hash solc-macos-aarch64 "$c"/macos-aarch64/"$s")
  };
}
EOF
    done
    echo "]"
} | tee "$T"/solc-listing.nix
